version: "3"

services:

    reverse-proxy:
        image: nginx:latest
        depends_on:
            db:
              condition: service_healthy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "./docker/nginx/node_server.conf:/etc/nginx/sites-available/node_server.conf"
            - "./docker/nginx/webapp.conf:/etc/nginx/sites-available/webapp.conf"
            - "./docker/nginx/init.sh:/usr/local/bin/init.sh"
            - "../api:/usr/share/nginx/html/api"
            - "../webapp:/usr/share/nginx/html/webapp"
            - ./certbot/www/:/var/www/certbot/:ro
        network_mode: host
        command: /bin/sh /usr/local/bin/init.sh

    certbot:
        image: certbot/certbot:latest
        volumes:
            - ./certbot/www/:/var/www/certbot/:rw
            - ./certbot/conf/:/etc/letsencrypt/:rw

    db:
        image: postgres:latest
        environment:
            POSTGRES_PASSWORD: '${PGPASSWORD}'
            POSTGRES_USER: '${PGUSER}'
            POSTGRES_DB: '${PGDB}'
            PGDATA: /db/postgres
        ports:
            - "5432:5432"
        command: postgres -c 'max_connections=1000'
        volumes:
            - ./data/postgresql:/var/lib/postgresql/db
        healthcheck:
            test: [ "CMD", "psql", "-U", "matanna", "-d", "tipsandtricks", "-c", "SELECT 1;" ]
            interval: 5s
            timeout: 1m
            retries: 15

